# Generated by Django 5.2.11 on 2026-02-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=1)),
                ('weekly_hours', models.IntegerField(default=2, verbose_name='ساعت در هفته')),
                ('for_all_grades', models.BooleanField(default=False, verbose_name='برای همه پایه\u200cها')),
                ('allow_split', models.BooleanField(default=False)),
                ('allow_without_teacher', models.BooleanField(default=False, verbose_name='میتواند بدون معلم باشد')),
                ('grades', models.ManyToManyField(blank=True, to='main.grade', verbose_name='پایه\u200cهای مرتبط')),
                ('paired_lessons', models.ManyToManyField(blank=True, to='main.lesson', verbose_name='درس\u200cهای پیشنهادی برای جفت شدن')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.grade')),
            ],
        ),
        migrations.CreateModel(
            name='DayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolday')),
            ],
            options={
                'ordering': ['day', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weekly_capacity', models.IntegerField(verbose_name='ظرفیت هفتگی (ساعت)')),
                ('limit_to_grades', models.BooleanField(default=False, verbose_name='محدود به پایه خاص')),
                ('grades', models.ManyToManyField(blank=True, to='main.grade', verbose_name='پایه\u200cهای مجاز')),
                ('lessons', models.ManyToManyField(to='main.lesson', verbose_name='درس\u200cهای قابل تدریس')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teachingassignment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dayperiod')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolclass')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher')),
            ],
            options={
                'unique_together': {('school_class', 'day_period'), ('teacher', 'day_period')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_hours', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolday')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'day')},
            },
        ),
    ]
