# Generated by Django 5.2.11 on 2026-02-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='lessons',
            field=models.ManyToManyField(to='main.lesson'),
        ),
    ]
