# Generated by Django 5.2.11 on 2026-02-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مدرسه')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='کد آموزشگاه')),
                ('education_level', models.CharField(max_length=100, verbose_name='مقطع تحصیلی')),
                ('manager_full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی مدیر')),
                ('manager_mobile', models.CharField(max_length=20, verbose_name='موبایل مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
