# Generated by Django 5.2.11 on 2026-02-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='day_periods',
            field=models.ManyToManyField(blank=True, to='main.dayperiod'),
        ),
        migrations.RemoveField(
            model_name='teacheravailability',
            name='day_period',
        ),
    ]
