# Generated by Django 5.2.11 on 2026-02-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_teacheravailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='teachingassignment',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='teachingassignment',
            name='school_class',
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='lesson',
            field=models.ManyToManyField(blank=True, to='main.lesson'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='school_class',
            field=models.ManyToManyField(blank=True, to='main.schoolclass'),
        ),
    ]
