# Generated by Django 5.2.11 on 2026-02-20 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dayperiod',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolday',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachingassignmentitem',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='dayperiod',
            constraint=models.UniqueConstraint(fields=('school', 'day', 'period_number'), name='uniq_period_per_school_day'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_grade_per_school'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_lesson_per_school'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('school', 'school_class', 'day_period'), name='uniq_schedule_per_school_class_period'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('school', 'teacher', 'day_period'), name='uniq_schedule_per_school_teacher_period'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_classname_per_school'),
        ),
        migrations.AddConstraint(
            model_name='schoolday',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_dayname_per_school'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_teacher_per_school'),
        ),
        migrations.AddConstraint(
            model_name='teacheravailability',
            constraint=models.UniqueConstraint(fields=('school', 'teacher', 'day'), name='uniq_availability_per_school_teacher_day'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('school', 'teacher'), name='uniq_assignment_per_school_teacher'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignmentitem',
            constraint=models.UniqueConstraint(fields=('school', 'assignment', 'school_class', 'lesson'), name='uniq_item_per_school_assignment_class_lesson'),
        ),
    ]
