# Generated by Django 5.2.11 on 2026-02-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_schoolprofile_manager_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='manager_full_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='manager_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
