# Generated by Django 5.2.11 on 2026-02-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacher_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='weekly_hours',
            field=models.IntegerField(default=2, verbose_name='تعداد ساعت در هفته'),
        ),
    ]
