# Generated by Django 5.2.11 on 2026-02-20 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_schedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayperiod',
            options={'ordering': ['day', 'period_number'], 'verbose_name': 'زنگ', 'verbose_name_plural': 'زنگ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'پایه', 'verbose_name_plural': 'پایه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'درس', 'verbose_name_plural': 'درس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'برنامه', 'verbose_name_plural': 'برنامه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'مدرسه', 'verbose_name_plural': 'مدارس'},
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name': 'کلاس', 'verbose_name_plural': 'کلاس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='schoolday',
            options={'verbose_name': 'روز', 'verbose_name_plural': 'روزها'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'دبیر', 'verbose_name_plural': 'دبیرها'},
        ),
        migrations.AlterModelOptions(
            name='teacheravailability',
            options={'verbose_name': 'حضور دبیر', 'verbose_name_plural': 'حضور دبیرها'},
        ),
        migrations.AlterModelOptions(
            name='teachingassignment',
            options={'verbose_name': 'تخصیص تدریس', 'verbose_name_plural': 'تخصیص\u200cهای تدریس'},
        ),
        migrations.AlterModelOptions(
            name='teachingassignmentitem',
            options={'verbose_name': 'آیتم تدریس', 'verbose_name_plural': 'آیتم\u200cهای تدریس'},
        ),
        migrations.RemoveConstraint(
            model_name='dayperiod',
            name='uniq_period_per_school_day',
        ),
        migrations.RemoveConstraint(
            model_name='grade',
            name='uniq_grade_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='uniq_lesson_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='uniq_schedule_per_school_class_period',
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='uniq_schedule_per_school_teacher_period',
        ),
        migrations.RemoveConstraint(
            model_name='schoolclass',
            name='uniq_classname_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='schoolday',
            name='uniq_dayname_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='teacher',
            name='uniq_teacher_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='teacheravailability',
            name='uniq_availability_per_school_teacher_day',
        ),
        migrations.RemoveConstraint(
            model_name='teachingassignment',
            name='uniq_assignment_per_school_teacher',
        ),
        migrations.RemoveConstraint(
            model_name='teachingassignmentitem',
            name='uniq_item_per_school_assignment_class_lesson',
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('school', 'name')},
        ),
        migrations.AlterField(
            model_name='dayperiod',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='main.schoolday'),
        ),
        migrations.AlterField(
            model_name='dayperiod',
            name='period_number',
            field=models.IntegerField(verbose_name='شماره زنگ'),
        ),
        migrations.AlterField(
            model_name='dayperiod',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='main.school'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام پایه'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.school'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='allow_split',
            field=models.BooleanField(default=False, verbose_name='اجازه جدا شدن (Split)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='allow_without_teacher',
            field=models.BooleanField(default=False, verbose_name='می\u200cتواند بدون معلم باشد'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='main.grade', verbose_name='پایه\u200cهای مرتبط'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='paired_lessons',
            field=models.ManyToManyField(blank=True, related_name='paired_with', to='main.lesson', verbose_name='درس\u200cهای پیشنهادی برای جفت شدن'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.school'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.school'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='main.grade'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام کلاس'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='main.school'),
        ),
        migrations.AlterField(
            model_name='schoolday',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال؟'),
        ),
        migrations.AlterField(
            model_name='schoolday',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام روز'),
        ),
        migrations.AlterField(
            model_name='schoolday',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='main.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='main.grade', verbose_name='پایه\u200cهای مجاز'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lessons',
            field=models.ManyToManyField(related_name='teachers', to='main.lesson', verbose_name='درس\u200cهای قابل تدریس'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دبیر'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='main.school'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='available_hours',
            field=models.IntegerField(verbose_name='ساعت\u200cهای مجاز'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availabilities', to='main.school'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='main.teacher'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='main.school'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.teacher'),
        ),
        migrations.AlterField(
            model_name='teachingassignmentitem',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.teachingassignment'),
        ),
        migrations.AlterField(
            model_name='teachingassignmentitem',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_items', to='main.lesson'),
        ),
        migrations.AlterField(
            model_name='teachingassignmentitem',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_items', to='main.school'),
        ),
        migrations.AlterField(
            model_name='teachingassignmentitem',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_items', to='main.schoolclass'),
        ),
        migrations.AlterField(
            model_name='teachingassignmentitem',
            name='weekly_hours',
            field=models.IntegerField(verbose_name='ساعت هفتگی'),
        ),
        migrations.AlterUniqueTogether(
            name='dayperiod',
            unique_together={('school', 'day', 'period_number')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('school', 'school_class', 'day_period'), ('school', 'teacher', 'day_period')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolday',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together={('school', 'teacher', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('school', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignmentitem',
            unique_together={('school', 'assignment', 'school_class', 'lesson')},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='priority',
        ),
    ]
