# Generated by Django 5.2.11 on 2026-02-12 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_teachingassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingassignment',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='teachingassignment',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='teachingassignment',
            name='weekly_hours',
        ),
        migrations.CreateModel(
            name='TeachingAssignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teachingassignment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolclass')),
            ],
        ),
    ]
