# Generated by Django 5.2.11 on 2026-02-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lesson_weekly_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='for_all_grades',
            field=models.BooleanField(default=False, verbose_name='برای همه پایه\u200cها'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='grades',
            field=models.ManyToManyField(blank=True, to='main.grade', verbose_name='پایه\u200cهای مرتبط'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='grades',
            field=models.ManyToManyField(blank=True, to='main.grade', verbose_name='پایه\u200cهای مجاز'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='lessons',
            field=models.ManyToManyField(to='main.lesson', verbose_name='درس\u200cهای قابل تدریس'),
        ),
    ]
