# Generated by Django 5.2.11 on 2026-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lesson_for_all_grades_lesson_grades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheravailability',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='teacheravailability',
            name='lessons',
        ),
        migrations.AddField(
            model_name='teacher',
            name='grades',
            field=models.ManyToManyField(blank=True, to='main.grade', verbose_name='پایه\u200cهای مجاز'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='limit_to_grades',
            field=models.BooleanField(default=False, verbose_name='محدود به پایه خاص'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lessons',
            field=models.ManyToManyField(to='main.lesson', verbose_name='درس\u200cهای قابل تدریس'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='weekly_capacity',
            field=models.IntegerField(verbose_name='ظرفیت هفتگی (ساعت)'),
        ),
    ]
