# Generated by Django 5.2.11 on 2026-02-21 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dayperiod_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBuildProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=0)),
                ('status', models.CharField(default='در انتظار...', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
        ),
    ]
