# Generated by Django 5.2.11 on 2026-03-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_schedulebuildprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce_title', models.CharField(max_length=1000, verbose_name='اطلاعیه سایت')),
                ('announce', models.BooleanField(default=False, verbose_name='فعال شدن اطلاعیه سایت')),
                ('announce_img', models.ImageField(blank=True, help_text='مهم :اندازه بنز به ارتفاع 80 پیکسل و طول 1400 پیکسل! رنگ پس زمینه عکس باید زرد روشن باشه', null=True, upload_to='announce', verbose_name='عکس بنر در صورت نیاز')),
                ('announce_link', models.CharField(max_length=1000, verbose_name='لینک صفحه مورد نظر')),
            ],
            options={
                'verbose_name': 'اطلاعیه سایت',
                'verbose_name_plural': 'اطلاعیه سایت',
            },
        ),
    ]
