# Generated by Django 5.2.11 on 2026-02-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_teacheravailability_grades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='weekly_hours',
            field=models.IntegerField(default=2, verbose_name='ساعت در هفته'),
        ),
    ]
