# Generated by Django 5.2.11 on 2026-02-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_schedule_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='paired_lessons',
            field=models.ManyToManyField(blank=True, to='main.lesson', verbose_name='درس\u200cهای پیشنهادی برای جفت شدن'),
        ),
    ]
