# Generated by Django 5.2.11 on 2026-02-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_lesson_paired_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='allow_split',
            field=models.BooleanField(default=True),
        ),
    ]
