# Generated by Django 5.2.11 on 2026-02-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_lesson_allow_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='allow_split',
            field=models.BooleanField(default=False),
        ),
    ]
