# Generated by Django 5.2.11 on 2026-02-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_lesson_allow_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='allow_without_teacher',
            field=models.BooleanField(default=False, verbose_name='میتواند بدون معلم باشد'),
        ),
    ]
